### ISSUE TITLE
Apollo Basics Tutorial - final section link missing?

### ISSUE THREAD

**Issue by bessfernandez** [apollographql/apollo#1019]
In the Apollo Basics tutorial in[ the last chapter (9)](https://www.apollographql.com/docs/tutorial/local-state)  at the end it states:

> Congratulations! 🎉 You've officially made it to the end of the Apollo platform tutorial. In the final section, we're going to recap what we just learned and give you guidance on what you should learn next.

Is this still in progress or maybe just missing a link here? A recap chapter would be great!

**Comment by StephenBarlow** [comment]
Thanks for reporting! The bottom of the final chapter now recommends next steps instead of referring to a nonexistent chapter.
