### ISSUE TITLE
Contributor Dashboard

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/apollo#105]
Hey everyone! 🙋 I'm looking to put together a project plan for an Apollo contributor dashboard and I need your input.

The dashboard will be a one stop shop for all information regarding the health of our repositories, feature request tracking, contribution metrics, and content aggregation. Here are some ideas I had in mind:

- Display all PRs open > 1 week across the organization
- Tag & query content (example: Find all content on GraphQL authentication across Medium, conference talks, and video tutorials)
- Upvote new features & content ideas (vote weight depends on your contribution level)

What metrics do you care about? What features would help reduce your maintenance burden and make your life easier? Please respond with your requests **in priority order**.

Ultimately, this project is all about you, so your feedback will be crucial to its success 🚀 thank you!

**Comment by jbaxleyiii** [comment]
*Project Status*
- Code-coverage
- Average CI build time
- Number of open issues by label (i.e. bugs / features / etc)

**Comment by NeoPhi** [comment]
- Most recent release (version & date)
- Commits since last release

**Comment by evans** [comment]
It might be nice to have some [metrics on repo traffic](https://github.com/apollographql/apollo/graphs/traffic) ([API](https://developer.github.com/v3/repos/traffic/))

**Comment by evans** [comment]
- [x] feature

/label good-first-issue

**Comment by JoviDeCroock** [comment]
Is there a repo for this? I wouldn't mind helping out on this one
