### ISSUE TITLE
GraphQL Patent Infringement Issues

### ISSUE THREAD

**Issue by subesokun** [apollographql/apollo#106]
Hi, maybe you've already followed the discussion in https://github.com/facebook/graphql/issues/351 . This issue got recently quite some attention like by GitLab (https://gitlab.com/gitlab-org/gitlab-ce/issues/34754) so I'm wondering what Apollo's opinion is on that topic. 

>  However, the current spec leads most implementations to be infringers.

> For the reasons set out above, most GraphQL users are likely infringing Facebook’s patents. Facebook should immediately include a patent grant into the GraphQL spec to stop justified panic and GraphQL abandonment.
https://medium.com/@dwalsh.sdlr/using-graphql-why-facebook-now-owns-you-3182751028c9

**Comment by stubailo** [comment]
We're aware of the issue. That issue is the right place to get updates, let's wait until Lee finishes the work he's currently doing, as he mentioned in the thread.
