### ISSUE TITLE
Subscriptions as a first-class citizen

### ISSUE THREAD

**Issue by dfee** [apollographql/apollo#107]
I'm not sure this is the right place to post this, so if not, please redirect me.

I'm not very interested in using `subscriptions-transport-ws` for my subscription transport. It's fine enough if you're using NodeJS on the backend, as you get the server side for free.

But for those of us who aren't using NodeJS on the backend, we need to either constantly update our code base to match changes to `subscriptions-transport-ws`, or roll our own subscription network interface.

I believe that is largely just writing a few function on a custom NetworkInterface object. But I don't see that documented anywhere – it doesn't appear to have a public facing interface. I think that oughta be documented [here](http://dev.apollodata.com/core/network.html#NetworkInterface).

Looking at the [client source](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/client.ts) of `subscriptions-transport-ws`, it looks like the functions needed for implementation are:
1) [`status`](https://github.com/apollographql/subscriptions-transport-ws/blob/v0.9.0/src/client.ts#L133)
2) [`close`](https://github.com/apollographql/subscriptions-transport-ws/blob/v0.9.0/src/client.ts#L141)
3) [`request`](https://github.com/apollographql/subscriptions-transport-ws/blob/v0.9.0/src/client.ts#L163)
4) [`unsubscribe`](https://github.com/apollographql/subscriptions-transport-ws/blob/v0.9.0/src/client.ts#L237)

I believe this used to be simpler... but alas, it's been a couple months since looking at this.

**Comment by dfee** [comment]
For additional background, I've figured out how to use socket.io for queries and mutations, but i'd like to go ahead and add subscriptions.

**Comment by dfee** [comment]
@evans any commentary on why you've closed this? Is it because the (now official) apollo client 2 uses apollo-link?

**Comment by evans** [comment]
@dfee Thank you for circling back! Yes I closed the issue, since apollo-client 2.0 uses apollo-link as the network layer.

If you figured out subscriptions with socket.io, then I think writing an adapter in the form of apollo-link-socket-io would be perfect. Does that fit with your thoughts?

Is there something more you are looking for with subscriptions as first class citizens?

**Comment by dfee** [comment]
Nope, not looking for anything else. I'm not sure I can add a complete JS solution for `apollo-link-socket-io` as my backend is Python. I'll consider pushing at least half of it though :)

Thanks for the response!
