### ISSUE TITLE
First tutorial is outdated

### ISSUE THREAD

**Issue by MarcelCutts** [apollographql/apollo#125]
Just went through the [first tutorial suggested](https://dev-blog.apollodata.com/full-stack-react-graphql-tutorial-582ac8d24e3b) on the Apollo documentation site.

I had to make a [number of adjustments](https://www.apollographql.com/docs/react/2.0-migration.html#install) due to changes introduced in Apollo Client 2 to reach the end of the tutorial.

There are also some inconsistencies in the provided CSS not matching the  classnames of the suggested JSX

I will have a brief dig around to see if there are any better candidates.

**Comment by mbj36** [comment]
+1

**Comment by erixtekila** [comment]
+1
You'd better remove this first bad discovering experience IMHO.

**Comment by JakeDawkins** [comment]
I'm going to close this, as I think it's resolved now. The docs sites should be much more up-to-date, and I couldn't find links referencing this blog post anymore
