### ISSUE TITLE
Can't run service:check before publishing

### ISSUE THREAD

**Issue by sandbochs** [apollographql/apollo#230]
While trying to publish my schema to Apollo Engine I ran into the issue described here: https://github.com/apollographql/apollo-tooling/issues/665. After some digging I found that schema is just an alias for service and was able to push and check against Apollo Engine. However, the tutorial doesn't mention that you need publish before being able to check.

I didn't open a docs PR because it's unclear to me if the the publishing step should be moved to a previous step so that the check command will actually produce a diff.

**Comment by StephenBarlow** [comment]
Thanks for reporting! The tutorial has since been updated to simplify the schema reporting process, and checks are no longer included in the content.
