### ISSUE TITLE
Broken Link on Main Website

### ISSUE THREAD

**Issue by ralph-dev** [apollographql/apollo#238]
/label Broken-Link

Source: https://www.apollographql.com/docs/resources/graphql-glossary.html#automatic-persisted-queries

Click on the HyperText "APQ" - (Automatic Persisted Queries (APQ).) Leads to this link which is empty.

Broken Hyperlink: https://www.apollographql.com/docs/guides/performance.html#automatic-persisted-queries

**Comment by StephenBarlow** [comment]
Looks like this broken link got fixed somewhere down the line. Thanks for reporting!
