### ISSUE TITLE
Error publishing schema when following tutorial

### ISSUE THREAD

**Issue by adokce** [apollographql/apollo#239]
When running `npx apollo schema:check && npx apollo schema:publish` as specified in https://www.apollographql.com/docs/tutorial/production.html#publish I get the following error:
![image](https://user-images.githubusercontent.com/20118440/48354951-35ae5a80-e693-11e8-9f9d-e382616573b1.png)

I followed the tutorial, my server was running in another terminal. I solved the problem by installing apollo and executing a command suggested by Apollo Engine website after creating a service

`apollo schema:publish --endpoint=http://localhost:4000 --key="service:<my-key>"`

At this point I compared my repo and finished repo. There seems to be a difference.
In the final server's index.js I found 

```
const internalEngineDemo = require('./engine-demo');
...
// and inside server setup
engine: {
    apiKey: process.env.ENGINE_API_KEY,
    ...internalEngineDemo,
  },
```

It may be related. I am not 100% sure why I didn't see these lines of code added or explained in tutorial.

Otherwise, thank you for this overall nice tutorial

**Comment by osteel** [comment]
Same here, had to follow Apollo Engine's suggestion:
```
$ npm i -g apollo
$ apollo schema:publish --endpoint=http://localhost:4000 --key="service:<my-key>"
```
`npx apollo schema:check && npx apollo schema:publish` produced the same result as in the comment above.

**Comment by yuwenhuang** [comment]
have the same problem, but I still get `No service found to link to Engine` after I add the following part in `index.js` and manually add `engine-demos.js`

```
const internalEngineDemo = require('./engine-demo');
...
// and inside server setup
engine: {
    apiKey: process.env.ENGINE_API_KEY,
    ...internalEngineDemo,
},
```
hopefully you can help to add more details to this deploy part of tutorial for newbies. I also get error 
`The content of "~/.now/auth.json" is invalid. No `token` property found inside`
after I follow the deploy instruction `npx now`

**Comment by maxgherman** [comment]
It's the **apollo shema:check** that gives this problem. The tutorial command has both, schema:check and schema:publish in it. This disguise a couple of problems:
First, local set up has to be explained. To publish a schema apollo needs 3 things: key, working endpoint and a service name. To set up the key, add it to the index.js

```js
engine: {
    apiKey: process.env.ENGINE_API_KEY
},
```  

Set up env variable  ENGINE_API_KEY for both consoles, the server and the publishing command.
Endpoint is given as part of the command line argument.
Service name could be specified as part of apollo.config.js file. Create one next to package.json with the content:

```js
module.exports = {
  service: {
    name: '<service name here>'
  }
};
```

Second, with the correct set up, schema:check still gives the error: "Could not find service <service> from Engine at ...", no matter how the command is executed: npx, global apollo, local apollo. So, to fix this problem, do not run schema:check first time you publish the service. All the subsequent executions shema:check works fine and detects all the changes.

**Comment by GeuntaBuwono** [comment]
so why you got an error `No service found to link to Engine` it's because you haven't run Apollo server 
to solve it you need to run your Apollo server first before you publish schema,

run your server with `yarn start` 
publish your schema with `apollo schema:publish --endpoint="http://localhost:4000" --key="<service-name>"`

**Comment by steephenvrs3** [comment]
idsygvf weuw efwej weygf ewgfe wewg podaaaaaaa

**Comment by smolinari** [comment]
Make sure your API key is complete. I ran into this too, only to realize I copied in just the hash and not the whole key.

The `.env` file entry should look like this:

`ENGINE_API_KEY=service:<service-name>:<hash-made-by-apollo-engine>`

The push to Apollo Engine worked perfectly after that. 

Scott

**Comment by stevemcghee** [comment]
I found that I mis-read the instructions, bypassing the critical point:

> make a copy of the `.env.example` file located in server/ and **call it `.env`**


so my .env.example had all the right stuff in it, but wasn't getting noticed :(

I'm guessing others might have had similar problems.

**Comment by ONE75** [comment]
Also, make sure you're in the correct folder when running the command: fullstack-tutorial/start/server (where .env is located)

**Comment by shakti97** [comment]
@yuwenhuang  ,The content of "~/.now/auth.json" is invalid.
 how you fix this up?

**Comment by mkamelali** [comment]
> Also, make sure you're in the correct folder when running the command: fullstack-tutorial/start/server (where .env is located)

To think that's why I was stuck...

**Comment by bschwartz757** [comment]
I got this error due to having my .env file inside `/start/server/src`. The .env file needs to be in the same workspace the terminal session running the publish command is in (i.e., if running `npx apollo service:push` from `/start/server`, your .env file must be in that directory.)

**Comment by Zacker112** [comment]
> Same here, had to follow Apollo Engine's suggestion:
> 
> ```
> $ npm i -g apollo
> $ apollo schema:publish --endpoint=http://localhost:4000 --key="service:<my-key>"
> ```
> 
> `npx apollo schema:check && npx apollo schema:publish` produced the same result as in the comment above.

Thanks it work fine!Thank you very much!!

**Comment by grantgeorge** [comment]
From tutorial root:

```
cd /start/server
npx apollo service:push --endpoint=http://localhost:4000
```
