### ISSUE TITLE
Add docs for the metrics reporting endpoint

### ISSUE THREAD

**Issue by zionts** [apollographql/apollo#277]
Enable other server implementors to integrate with Apollo Engine's reporting functionality. This should essentially describe the format for reporting metrics as well as other resources in creating a metrics reporting agent like Apollo Engine Reporting.

**Comment by daniman** [comment]
Closing because we have a doc for this now! https://www.apollographql.com/docs/platform/setup-analytics.html#Engine-reporting-endpoint
