### ISSUE TITLE
Datadog Learn More link incorrect

### ISSUE THREAD

**Issue by epitaphmike** [apollographql/apollo#282]
The Datadog "Learn More" link on the Engine Integrations page points to "https://www.apollographql.com/docs/engine/integrations/datadog.htmL"

There is a capital "L" in html which leads to a Page Not Found.

The link should be "https://www.apollographql.com/docs/engine/integrations/datadog.html"

<img width="675" alt="screen shot 2018-12-09 at 7 45 04 pm" src="https://user-images.githubusercontent.com/677832/49705211-0552d100-fbeb-11e8-84f3-ef6e2a03a45c.png">

**Comment by daniman** [comment]
Hi @epitaphmike! Not sure what was up here and I know it's been a while since you opened this issue. I checked this link from the Engine UI and it seems to be working fine now 🤷‍♀️ 

I'm going to close this issue, but please re-open it if it's still broken for you.
