### ISSUE TITLE
FYI, WIP on tutorial docs

### ISSUE THREAD

**Issue by smolinari** [apollographql/apollo#293]
Hi,

I was hoping to get finished yesterday, but I ran into so many issues with section 6, that I couldn't finish. I'm working on getting the tutorial to work. I've fixed some issues. But, section 6 needs a lot of work. The explanations simply do not lead to working code.

So, please consider my work WIP! 😄 

Any comments on what I have done up till now would be appreciated. I'd just like to know if this work is welcomed or shunned. Good or bad. No worries. 

Scott

**Comment by smolinari** [comment]
BTW, it might be smarter to move the tutorial docs to [the tutorial repo](https://github.com/apollographql/fullstack-tutorial). It would make more sense than making noise with these issue in the apollo repo. 😃 

Scott

**Comment by breynolds** [comment]
Same issue here. Up to section 4 everything was great. Then I got to sections 5 & 6 and it's so incomplete that I can't get anything to to work. There's nothing that talks about how to actually run the client side. There's a reference to "Open your console" but no discussion about what that means. I did try debugging that code in VS Code and viewing the console, but the code didn't actually work.

**Comment by smolinari** [comment]
After finishing the docs review, I am now definitely of the opinion section 4 should be moved to the latter sections under "PLATFORM". 

Scott
