### ISSUE TITLE
Tutorial – various smaller fixed and improvements

### ISSUE THREAD

**Issue by borekb** [apollographql/apollo#329]
Hi, I went through your tutorial – it's amazingly well done! I encountered several smaller issues along the way for which I've submitted a couple of pull requests. They are across repositories so I'm creating this issue as an overview.

- [x] = merged

Formatting and other small fixes:

- [x] Fix Markdown formatting in `client.md` https://github.com/apollographql/apollo/pull/315
- [ ] Use `yarn` instead of `npm install` https://github.com/apollographql/apollo/pull/316
- [x] Tutorial 7: clarify how to test the login form https://github.com/apollographql/apollo/pull/319
- [ ] Improve heading structure in tutorial no. 7 https://github.com/apollographql/apollo/pull/320

Fixes in code examples (sometimes needs synchronization with `apollographql/fullstack-tutorial`):

- [ ] Code example in `client.md` https://github.com/apollographql/apollo/pull/317
- [ ] Scaffold React components so that initial demo runs https://github.com/apollographql/fullstack-tutorial/pull/64 (resolves issue https://github.com/apollographql/fullstack-tutorial/issues/63)
- [ ] Fixed code example in Mutations tutorial https://github.com/apollographql/apollo/pull/318
- [x] Fix code example in local state (missing `StyledButton`) https://github.com/apollographql/apollo/pull/323

**Comment by borekb** [comment]
Not sure who to tag but could somebody take a look please? The PRs will probably get stale quickly.

**Comment by daniman** [comment]
Hi @borekb! Thanks so much for opening all these PRs and sorry for the delay on our side. We've gone through and updated all your PRs (most are merged), so I'm going to go ahead and close this issue for now. Thanks so much for contributing :)
