### ISSUE TITLE
Consistency over various repositories

### ISSUE THREAD

**Issue by JoviDeCroock** [apollographql/apollo#338]
This isn't really a feature request but something that has been bothering me when contributing to apollo. It iss the constant need to check "oh, is this repository using yarn or npm" since using the wrong one won't follow along with the respective lockfile.

This proposal has two solutions;
1. Choose one for all repo's
2. Make a preinstall script that checks what you are installing with and throw if it's the wrong one, something in the lines of: ```"preinstall": "node -e \"if (process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('Use yarn for installing: https://yarnpkg.com/en/docs/install')\""```

I think the latter has the least implications since this won't force any repo's to convert their lockfile to the other.

**Comment by JoviDeCroock** [comment]
Graphql-tag being the first of them, it uses yarn.

**Comment by JakeDawkins** [comment]
Ah, good catch! Yeah, from my understanding, npm should be the route to go. If we're not doing it in some repos, I'd just open an issue in them to get feedback. Most likely, it's just a result of that not being updated in a while.

Are you fine with me closing this issue @JoviDeCroock ?

**Comment by JoviDeCroock** [comment]
Totally fine, I'll make an issue on gql tag thanks for the clarification!
