### ISSUE TITLE
"Edit on Github" bad link

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo#383]
Eg:

https://www.apollographql.com/docs/tutorial/data-source

"Edit on Github" links to:

https://github.com/apollographql/apollo/tree/HEAD/docs/source/tutorial/data-source.md

which redirects to:

https://github.com/apollographql/apollo/blob/46fe74535b196cba489a49738a7fe8db2f8c7674/docs/source/tutorial/data-source.md

which is not editable. Think should be:

https://github.com/apollographql/apollo/blob/master/docs/source/tutorial/data-source.md

or `tree/master`, which redirects to above. So would be fixed if `tag` were `'master'` instead of `'HEAD'` here:

https://github.com/apollographql/gatsby-theme-apollo/blob/master/packages/gatsby-theme-apollo-docs/src/components/page-content.js#L226

**Comment by zionts** [comment]
Seems to be fixed by #384 thanks!
