### ISSUE TITLE
Is service check removed from Apollo Engine free plan?

### ISSUE THREAD

**Issue by xcv58** [apollographql/apollo#388]
I use apollo@2.8.1.

The log after `apollo service:check -c=apollo.config.js`

```
  ✔ Loading Apollo Project
  ⠼ Validating local schema against tag current on service xxx-dev
    → Validating schema
  ✔ Loading Apollo Project
  ✖ Validating local schema against tag current on service xxx-dev
    → https://engine.apollographql.com/upgrade.
    Comparing schema changes
    Reporting result
Error: A service check is not available for your current plan.
To run a service check, please upgrade:
https://engine.apollographql.com/upgrade.
    at execute.then (~/work/physiou-graphql/web/node_modules/apollo-language-server/lib/engine/index.js:43:23)
    at <anonymous>
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by zionts** [comment]
Hi @xcv58 the feature was always intended to only be available to paid plans, but you can upgrade to a trial to have access. Our support team will be happy to work with you (engine.apollographql.com/support) if this is a feature you've been relying on. Really sorry for the lack of notice here!

**Comment by daniman** [comment]
Hi @xcv58! I wrote a comment explaining what happened here on Spectrum: https://spectrum.chat/apollo/apollo-platform/apollo-platform-pricing-contradiction~a7fac77b-5a5f-45bf-9bfa-5a730402aee9?m=MTU1NTAwMTMxNzQ0Mg==. Really sorry for the inconvenience.

**Comment by xcv58** [comment]
Thank you, guys!
