### ISSUE TITLE
TLS configuration for encrypted private key

### ISSUE THREAD

**Issue by bencmbrook** [apollographql/apollo#395]
Under Frontend TLS, one can specify a `certificateFile` and `keyFile`.
https://github.com/apollographql/apollo/blob/master/docs/source/references/proxy-config.md#frontendtls

It's a best practice to keep the private key files encrypted with a passphrase. Is there any support for passing the passphrase into this configuration?

For example, see the `passphrase` option in Node's `TLS.createSecureContext`
https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options

**Comment by zionts** [comment]
@bencmbrook Since the proxy is deprecated, there are no plans on adding that feature into the configuration. Can you think of any workarounds?

**Comment by daniman** [comment]
@bencmbrook I'm going to close this issue since the Engine proxy is not maintained anymore. We'd love to help you and your team build a direct integration to our reporting agent so you can move off of the Engine proxy if you're interested :)
