### ISSUE TITLE
"Discuss on Spectrum" link is broken for the Platform docs

### ISSUE THREAD

**Issue by daniman** [apollographql/apollo#399]
It links here, which doesn't exist: https://spectrum.chat/apollo/apollo?tab=posts

**Comment by zionts** [comment]
@daniman where is that? I only see links to `spectrum.chat/apollo` from my grep

**Comment by dcorb** [comment]
https://github.com/apollographql/gatsby-theme-apollo/pull/32

**Comment by dcorb** [comment]
![image](https://user-images.githubusercontent.com/881333/56245840-1041d480-60a9-11e9-859c-9d67040b520b.png)

**Comment by daniman** [comment]
#419

**Comment by daniman** [comment]
Fixed by #419
