### ISSUE TITLE
GraphQL playground is blank when following tutorial to build up schema

### ISSUE THREAD

**Issue by nick1ee** [apollographql/apollo#449]
Hi there,
I'm new to GraphQL, so I just follow the tutorial and build up the schema. After I launched the local graphql server and visit by http://localhost:4000, I found nothing here except the graphql loading animation. Can anyone tell me how to debug? or where is the log that I could check? 
All your comments will be appreciated. Thanks!

Tutorial link:
https://www.apollographql.com/docs/tutorial/schema#write-schema

my forked repo:
https://github.com/nick1ee/fullstack-tutorial

**Comment by TheVedhaGuy** [comment]
I run into a similar issue except the playground doesn't seem to load 

![image](https://user-images.githubusercontent.com/14185832/58103581-35969680-7bb1-11e9-86b6-4b317f819c7d.png)

**Comment by TheVedhaGuy** [comment]
However, I did find someones 'quick fix' solution online. In `package.json` change `apollo-server` and `apollo-server-testing` to version `2.5.0`

**Comment by chrisrwPWC** [comment]
This didn't work for me, I still receive the same error as mentioned above.

**Comment by chrisrwPWC** [comment]
> However, I did find someones 'quick fix' solution online. In `package.json` change `apollo-server` and `apollo-server-testing` to version `2.5.0`

Can you link to the quick fix you found?

**Comment by odigity** [comment]
I had the same experience - localhost:4000 briefly shows a loading animation, then nothing but a blank dark blue page.

Perhaps it has something to do with all the warnings I experienced when I ran `npm install` in the start/server directory, as instructed at the beginning of the tutorial.  Here's the output of that:

https://gist.github.com/odigity/2ae1f357ecaafa0eaac351527245ca10

**Comment by tylonw** [comment]
> However, I did find someones 'quick fix' solution online. In `package.json` change `apollo-server` and `apollo-server-testing` to version `2.5.0`

This worked for me after running `npm install` again and restarting the server (`npm start`).

**Comment by nick1ee** [comment]
It seems like the fix is to update `apollo-server` and `apollo-server-testin` to version `2.5.0`, then run `npm install` and `npm start` to restart the server. Thanks @TheVedhaGuy !

**Comment by odigity** [comment]
Shouldn't someone open an issue here so it actually gets fixed?

https://github.com/apollographql/fullstack-tutorial/issues

**Comment by BVasilev-zz** [comment]
I had the exact same issue. What fixed it was changing my browser from Firefox to Chrome.
