### ISSUE TITLE
Client awareness to track users?

### ISSUE THREAD

**Issue by booboothefool** [apollographql/apollo#464]
So I understand client awareness can be used to track clients like "what versions of my iOS app are using this query?", but is it the also the solution I'm supposed to use to track things like "what users are using this query?" as well? It's meant to track clients, but I'm asking if it can be fine-grained enough to track users to discover things like "the most useful query to user Bob is someQuery", or if I'm supposed to use something else for that? Thanks.

**Comment by daniman** [comment]
Absolutely! It's meant to be used for tracking client name and version, like iOS version 2.1.3, but not meant for user-granularity analytics. For that we recommend another tool suited for specifically tracking user events :)
