### ISSUE TITLE
Apollo Engine should not accept empty tag/variant

### ISSUE THREAD

**Issue by jhanschoo** [apollographql/apollo#578]
I've accidentally pushed a graph with an empty tag/variant using

    apollo service:push --tag=""

The push succeeded, but the web interface does not handle the empty tag well. Apollo Engine should not accept pushes with an empty tag/variant.

**Comment by StephenBarlow** [comment]
Thanks for reporting! Now, any Apollo tooling that accepts the empty string for a variant converts it to the default variant name (`current`).
