### ISSUE TITLE
Some search results link to 404 page not found

### ISSUE THREAD

**Issue by vfonic** [apollographql/apollo#581]
I was just trying to find some information on the best practices regarding user authentication.

First, I landed from a search engine to a 404 page. 🤷‍♂ 

Then I clicked on "Back to our site" link on that page and typed `auth` in the search box. All the links under "Apollo server" link to 404 page. There's only one link remaining under "Apollo Angular" and that one links to existing page.

**Comment by s-pace** [comment]
👋 @vfonic 

(I am part of the DocSearch team which builds the search index for the apollo documentation)

Could you give it a new try please? I do think this issue is no longer existing.

If it is, please attach a query example with a screenshot of the 404 result you have clicked on. 

Thanks 🙏

**Comment by vfonic** [comment]
Seems to be working now. Thanks!
