### ISSUE TITLE
Apollo Docs pointing to old apollo githuba account

### ISSUE THREAD

**Issue by ricardovsilva** [apollographql/apollo#592]
Links on bottom of connectors page are pointing to an older apollo github account.
![image](https://user-images.githubusercontent.com/2130182/65277040-71aa1b80-daff-11e9-978f-30d207e32fa4.png)

**Comment by StephenBarlow** [comment]
Thanks for reporting! This documentation set has been decommissioned, and the canonical [graphql-tools docs are here](https://www.graphql-tools.com/docs/introduction/).
