### ISSUE TITLE
Typo in Getting Started

### ISSUE THREAD

**Issue by stemmlerjs** [apollographql/apollo#646]
Hey folks,

I found a couple of small typos in the "Getting started" modal from the app.

> Our editor integration offers intelligent autocomplete and ~metircs~ metrics, 
enhancing your editor with rich metadata about ~yoru~ your graph API.

![Screen Shot 2019-10-14 at 11 52 32 PM](https://user-images.githubusercontent.com/6892666/66799102-cc0b8180-eedd-11e9-93a6-65eb238442b7.png)

**Comment by StephenBarlow** [comment]
Oh snap was this before you started?! Thanks for reporting 😄
