### ISSUE TITLE
Missing import in Step 8 of tutorial

### ISSUE THREAD

**Issue by robguinness** [apollographql/apollo#698]
In [Step 8](https://www.apollographql.com/docs/tutorial/local-state/) of the tutorial, the code fragments under [Adding virtual fields to server data](https://www.apollographql.com/docs/tutorial/local-state/#adding-virtual-fields-to-server-data) are missing an import of `GET_CART_ITEMS`. It would be better to show this import, so the person following along doesn't get confused.

**Comment by StephenBarlow** [comment]
The local state chapter has been revamped to use Apollo Client 3, so this should now be resolved. Thanks for reporting!
