### ISSUE TITLE
Tutorial directs user to write directly on cache (not client object)

### ISSUE THREAD

**Issue by ScorpIan555** [apollographql/apollo#739]
I'm running thru this tutorial after having used Apollo Client w/ a different GQL back-end a while back.  I specifically remembered this from the ApolloClient docs:

**Important: You should call these methods on your app's ApolloClient object, not directly on the cache. By doing so, the ApolloClient object broadcasts cache changes to your entire app, which enables automatic UI updates. If you call these methods directly on the cache instead, changes are not broadcast**

from this page in the documentation:
https://www.apollographql.com/docs/react/caching/cache-interaction/

In this scenario, I'm thinking the docs are right here.  If I just replace the 'cache' object with the 'client' object, is there anything else I might be missing (down the line, that is)?

**Comment by StephenBarlow** [comment]
Thanks for reporting! The tutorial has since been updated to use Apollo Client 3 local state APIs, and this inconsistency is no longer present.
