### ISSUE TITLE
How to properly deliver error in resolver?

### ISSUE THREAD

**Issue by zhaoyao91** [apollographql/apollo#76]
For example, we have a mutation `createUser`, inside the resolver of which we should check if the mail is duplicate, and if so, throw an error(or by other means?).
On the client, we call the mutation and should display different types of messages by the error.

In Meteor, we have MeteorError, which contains error, message and detail. But in Apollo, if we just throw an Error, it can only carry a message, which is not convenient to process.

**Comment by GGAlanSmithee** [comment]
Might be misunderstanding you here, but if you know the type of the error on the server, you can just return the appropriate message, and display it on the client. If you need to know what to of error occurred client side, you can return any additional info for your client to consume, for example;

```javascript
return {
    success: false,
    type: ErrorType.Unauthorized,
    message: "wrong credentials"
}
```
And if you're using a DB abstraction, such as sequelize, you can just pass validation errors.

**Comment by zhaoyao91** [comment]
@GGAlanSmithee for a graphql resolver, you can't return fields which is not defined in the Type of this mutation. for example, you have `mutation createUser(...): User`, you can't return fields such as success, type and message.

I am curious about if there is some similar way like what Meteor does: wrap the error with more useful fields.

**Comment by GGAlanSmithee** [comment]
Yeah, you are right, the way I do it is to include `success` and `message` in addition to any other payload

```javascript
{
    success: true / false,
    message: errorMessage,
    data: createdUser
}
```

So, if `success` (or status code if more than binary results) is `false`, `message` contains explanation, and if it's `true`, `data` contains any other data.

But, yeah, I understand that you are asking for a standardised (integrated) way of doing this, in which I would be interested too.

**Comment by helfer** [comment]
@zhaoyao91 In GraphQL there are two possible approaches:

1. Throw an error and return a message (not what you want, you say)
2. Use a GraphQL union of YourErrorType and YourDataType and then select the appropriate one with fragments.

Which way is better usually depends on what kind of error it is.

I know this probably isn't the answer you're looking for, but because Apollo is just implementing GraphQL, this discussion really belongs on https://github.com/graphql/graphql-js

**Comment by zhaoyao91** [comment]
@helfer thanks, your solution 2 is really inspiring.
May I know how do you handle such case? How do you tell the client the failure of the mutation in your apps?

**Comment by zhaoyao91** [comment]
Hi @GGAlanSmithee, how to include extra fields to the result of the resolver? If I return something in the resolver, it becomes the data.createUser part automatically.
