### ISSUE TITLE
Clarification in tutorial

### ISSUE THREAD

**Issue by mgilarmo** [apollographql/apollo#765]
Hi, 
On step 3 of the tutorial ("Write your graph's resolvers"), I thought I would offer a slight clarification for the instruction that says "Now, let's add the resolvers for bookTrips and cancelTrip to Mutation"

You provide a snippet of code to copy: 
```
Mutation: {
  bookTrips: ...
  cancelTrip: ...
}
```

Since there was a previous instruction to create `Mutation: {login: ...}`, I wasn't clear on if the second instruction meant to add a second `Mutation` type (in addition to the one with login resolver) or if I was supposed to paste over the existing one or if I was just adding the two additional resolvers to the same `Mutation` type.

Although it made most sense to add to the existing one, the fact that the copyable snippet started with `Mutation {...}` added confusion.

I think it would be clearer to say, "Now, let's add the resolvers for bookTrips and cancelTrip under the resolver for login:"  and then remove the `Mutation` wrapper from the copyable snippet.

**Comment by StephenBarlow** [comment]
Thanks for reporting! This has since been clarified with code comments in the chapter.
