### ISSUE TITLE
Add "module" entry to package.json of all packages

### ISSUE THREAD

**Issue by jaydenseric** [apollographql/apollo#78]
It would be great if all transpiled Apollo packages had a package.json `module` entry, pointing to an ES modules build. Modern tools such as Rollup and Webpack 2 prefer to consume ESM to do better tree-shaking, etc. It's also a lot nicer to read when debugging than CJS transpilation output.

See [the Rollup wiki entry](https://github.com/rollup/rollup/wiki/pkg.module), and [this Webpack issue](https://github.com/webpack/webpack/issues/1979).

Creating an issue here first for discussion, instead of in each individual repo.

**Comment by helfer** [comment]
@jaydenseric I'm not very familiar with the intricacies of packaging, but that sounds like a reasonable thing to do. I believe we already have it for Apollo Client, and @calebmer was planning to improve it and also change the build of react-apollo.

**Comment by helfer** [comment]
Hey @jaydenseric, I think we have modules for apollo-client. Which specific repos would you like to have module entries for? Feel free to make PRs to add them there.
