### ISSUE TITLE
cache.writeData() call has already been declared

### ISSUE THREAD

**Issue by fsultani-atm** [apollographql/apollo#798]
Minor issue, but for code highlighting consistency, [Initialize the store](https://www.apollographql.com/docs/tutorial/local-state/#initialize-the-store) should not have `cache.writeData()` highlighted as new code since it was already added in the [previous step](https://www.apollographql.com/docs/tutorial/mutations/#attach-authorization-headers-to-the-request).  I believe only `typeDefs` and `resolvers` should be highlighted.

**Comment by StephenBarlow** [comment]
Thanks for reporting! This chapter has since been overhauled to use Apollo Client 3 local state APIs instead of `cache.writeData()`.
