### ISSUE TITLE
Step 4 of tutorial needs more troubleshooting tips, can't connect

### ISSUE THREAD

**Issue by amoskane** [apollographql/apollo#815]
I had a really hard time connecting because the tutorial and the instructions on engine.apollograph.com differ. Looking up past issues gives you even more combinations, and when you add in syntax errors, this becomes a 6 hour step. Some suggestions for helpful tips:

-You might be adding a `user:` instead of a `service:` if that's what engine.apollograph.com tells you to do. So you might have 
`ENGINE_API_KEY=user:gh.<username>:E4VSTiXeFWaSSBgFWXOiSA` 
instead of 
`ENGINE_API_KEY=service:my-service-439:E4VSTiXeFWaSSBgFWXOiSA`

-If `npx apollo` says it can't find the service and you know it's published, double check that your email is verified and reboot.

-You shouldn't have to specify a `--key` in your terminal command if everything else is set up correctly

-Here's a 1-line description of how service:push, schema:publish, and schema:check differ.

-Make sure that when you run your `npx apollo` command, you are in the same folder as where you started your server

-Here's why `apollo` won't run without `npx `even though you installed in globally

Without these, it won't work! Seems important enough to publish! Happy to make a PR but instructions said to float the idea first, so let me know.

**Comment by samjulien** [comment]
Came here to file the same issue; got really tripped up at this part of the tutorial. I think just a few clarifying lines or notes (e.g. "be sure to `cd` back into the `server` folder") would make all the difference. There's also nothing in the tutorial about creating the `apollo.config.js` file that the service tells you to create.

**Comment by StephenBarlow** [comment]
Thanks for reporting! This chapter has since received substantial content updates and the process to connecting to Studio has been simplified.
