### ISSUE TITLE
Unable to find APOLLO_KEY error when configuring the Graph Manager setup for my project

### ISSUE THREAD

**Issue by lfa9603** [apollographql/apollo#827]
Currently getting the following error:
![image](https://user-images.githubusercontent.com/36972588/78077592-1db0b580-7405-11ea-929d-baac68748360.png)

After running the following command: 
`
npx apollo service:push --endpoint=http://localhost:3001/graphql
`

This happens after I created a project using apollo-server-express and linked the Apollo Server to my Express app on port 3001.
My server Apollo Server configuration is the following:
`
const server = new ApolloServer({
    typeDefs,
    resolvers,
    engine: {
        apiKey: process.env.ENGINE_API_KEY,
        schemaTag: 'development',
    },
});
`
I also tried substituting ENGINE_API_KEY with APOLLO_KEY as this is the only key Apollo gives me to manage but it was unsuccessful.

I also noticed 4 days ago PR #822 regarding the deprecation of ENGINE_API_KEY was open. Am I missing something or is there an issue at the moment?

**Comment by djma777** [comment]
same problem here 
```bash
 npx apollo service:push --endpoint=http://localhost:31513/graphql
 »   Warning: [Deprecation warning] Setting the key via ENGINE_API_KEY is
 »   deprecated and will not be supported in future versions.
```

and it fails...
```bash
Loading Apollo Project [started]
Loading Apollo Project [completed]
Uploading service to Apollo Graph Manager [started]
Uploading service to Apollo Graph Manager [failed]
→ ServerError: Response not successful: Received status code 400
Error: ServerError: Response not successful: Received status code 400
```

**Comment by mokyox** [comment]
You'll need to add an `apollo-config.js` file with the following configuration:

```
module.exports = {
  service: {
    name: <name-of-your-graph>
  }
}
```

Someone made a PR for this so hopefully it gets fixed soon. https://github.com/apollographql/apollo/pull/817

**Comment by DanielG94** [comment]
Had the same problem on windows when I run the command via powershell. Starting powershell as administrator solved this - for some reason it didn't find the .env file without adminsitrator privileges

**Comment by lfa9603** [comment]
@DanielG94 it worked, thank you for the help.
