### ISSUE TITLE
Better handling errors (Validation)

### ISSUE THREAD

**Issue by hmontes** [apollographql/apollo#83]
In a app with mongoose (mongoDB) with their Schema and validation rules. If i call a function for create account and the validator fails (example. Repeated email and blank password field) the function send an error.

The problem? Apollo only allows one argument (the message) for the error (in a promise with reject command). So, If i'm doing a multilanguage app, the error handle becomes very difficult.
 
1) How can i include a "type"? {type: 'email', message: 'email don't unique') in the error?
2) If my app is multilingual? How can i handle the error in the client? Maybe with a error code?
3) I try to put an array but i can´t'. How can i handle multiple errors?

Thanks and sorry for my bad english.

Example code.
Resolver

```
module.exports = {
  RootQuery: {
    users() {
      return User.find({});
    }
  },
  Mutation: {
    registerUser(_, data) {
      return register(data);
    }
  }
};
```

Register Controller
```
exports.register = function(data) {
  const { email, password } = data;
  const user = new User({
    email,
    password,
  });

  return new Promise((resolve, reject) => {
    user.save().then((user) => {
      resolve(user);
    }).catch((err) => {
      reject(error);
    });
  });

};

```

**Comment by savovs** [comment]
+1 I'm also looking for best practices for sending errors to users.

**Comment by helfer** [comment]
Hey @hmontes. You can use the `formatError` function on the server to decide which fields to send to the client. I hope that helps!

I'm closing this issue here, because it's not the right repo. Open it either on graphql-server or apollo-client if you'd like to discuss further 🙂

**Comment by hmontes** [comment]
Sure. I'm using this approach. Check please:

formatError: (err) => {
        if (err.message.indexOf('::') > -1) {
          const errorSplit = err.message.split('::');
          const newErr = {
            name: errorSplit[0],
            message: errorSplit[1]
          };
          return newErr;
        }
        return err;
      }

Is not the best way. But i can handle the error (with Throw new Err or reject) with 'someName::message'. So, i can return the name or type of the error in the client (example. Field) and a message with the traslated and customized message for the language.

What do you think @helfer ?
