### ISSUE TITLE
 Setting the key via ENGINE_API_KEY is deprecated and  will not be supported in future versions

### ISSUE THREAD

**Issue by EthanSK** [apollographql/apollo#839]
Im getting this warning when using apollo engine:

 Setting the key via ENGINE_API_KEY is deprecated and will not be supported in future versions.

The official docs tell you to set ENGINE_API_KEY in .env though!!

**Comment by zionts** [comment]
I think this should be resolved by https://github.com/apollographql/apollo/pull/878, but please reopen if you still see an issue!
