### ISSUE TITLE
Connect middleware with afterware

### ISSUE THREAD

**Issue by andreasgruenh** [apollographql/apollo#84]
Hello everyone, I have been replacing Relay with Apollo in my SPA and I'm really liking it so far! One problem I encountered is refering to the middlewares.
In the past I had a logging middleware in my fetchWrapper, that logs the path, the response, and the time to completion. Is this possible with the model of middlewares and afterwares?
Why can't the next() function in the middleware return the request promise, so that you can have request specifig state before and after the request?

**Comment by helfer** [comment]
Hey @andreasgruenh! This repo doesn't contain any code. Can you open this issue on apollo-client instead? Thanks!
