### ISSUE TITLE
Cannot make first client query from part 5 in the tutorial + tutorial improvements

### ISSUE THREAD

**Issue by mokyox** [apollographql/apollo#843]
I'm getting this an import error when I run `npm start` to make our first client query on part 5 of the tutorial - [connecting your API to a client.](https://www.apollographql.com/docs/tutorial/client/)

Here is the error:

```
/Users/Mo/Documents/GraphQL/fullstack-tutorial/start/client/src/containers/cart-item.tsx
TypeScript error in /Users/Mo/Documents/GraphQL/fullstack-tutorial/start/client/src/containers/cart-item.tsx(6,10):
Module '"../../../../../../../../../Users/Mo/Documents/GraphQL/fullstack-tutorial/start/client/src/pages/launches"' has no exported member 'LAUNCH_TILE_DATA'. Did you mean to use 'import LAUNCH_TILE_DATA from "../../../../../../../../../Users/Mo/Documents/GraphQL/fullstack-tutorial/start/client/src/pages/launches"' instead?  TS2614

    4 | 
    5 | import LaunchTile from '../components/launch-tile';
  > 6 | import { LAUNCH_TILE_DATA } from '../pages/launches';
      |          ^
    7 | import * as LaunchDetailTypes from '../pages/__generated__/LaunchDetails';
    8 | 
    9 | export const GET_LAUNCH = gql`

```

Is anyone else getting this? I can't seem to solve it with jiggling around `LAUNCH_TILE_DATA` imports and copying the data from from `final/client`. Any ideas?

### Tutorial Improvements

The same part 5 of the tutorial needs some updating in order to work correctly.

It says:

> Next, create an Apollo config file called apollo.config.js. This config file is how you configure both the Apollo VSCode extension and CLI. Paste the snippet below into the file:

> 

 ```
 module.exports = {
  client: {
    name: 'Space Explorer [web]',
    service: 'space-explorer',
  },
};
```

However,  what we actually need is :
```
module.exports = {
  client: {
    service: 'my-graphql-app'
  }
};
```

Where `service` is the ID of the graph we've created in Apollo Graph Manager.

 The Apollo documentation [here](https://www.apollographql.com/docs/devtools/editor-plugins/) is up-to-date - it's a simple copy-paste job, I would be happy to do that if it's OK.  😀

**Comment by CluEleSsUK** [comment]
I indeed had the same problem.  I turned the import into a default import (i.e. to `import LAUNCH_TILE_DATA from '../pages/launches';`) and replaced the `.LaunchTile` with `id`.

As I got further in the tutorial, I was unable to `npm run codegen` successfully, as I got the following error:
```
  ✖ Generating query files with 'typescript' target
    → Apollo does not support anonymous operations
Press any key to stop.
(node:83901) UnhandledPromiseRejectionWarning: GraphQLError: Apollo does not support anonymous operations
```.

Looking in my schema and in the playground, I don't appear to have any anonymous operations however, so it's quite puzzling! If anyone has any insight I'd be happy to hear.  Sorry to hijack your issue a little - tbh though I'm not sure my above fixes are _really_ fixes, they just get me to the next bug in the tutorial ;)

**Comment by damirJa** [comment]
This is my solution. I just took the code from the final version of a project. In the commit comments, I found that guys planed before to make more steps in the tutorial but then give more done code just without explaining it.
```
import gql from 'graphql-tag';

export const LAUNCH_TILE_DATA = gql`
    fragment LaunchTile on Launch {
        __typename
        id
        isBooked
        rocket {
            id
            name
        }
        mission {
            name
            missionPatch
        }
    }
`;
```

**Comment by mokyox** [comment]
@damirJa Thanks, that seems to have solved it. :) I added that code to `start/client/src/pages/launches.tsx` and it allows the front end to compile successfully.

Just a heads up: For this to work up at this stage the shape of the `LAUNCH_TILE_DATA` should be:

```
 mission {
            missionPatch
          }
```

without the `name` field. 

Otherwise you get an error in the console in developer console: `Uncaught (in promise) Error: Network error: Response not successful: Received status code 400`. but the front end actually compiles and doesn't show any errors. 

Also the Network tab shows an error with the response: `message: "Cannot query field "name" on type "Mission"`

@CluEleSsUK Thanks and no worries. Have a go trying out the solution posted above and seeing how it works out for you. If not, have you checked out if your types are named? I see someone had an issue with a similar error here

**Comment by mokyox** [comment]
@damirJa Thanks, that seems to have solved it. :) I added that code to start/client/src/pages/launches.tsx and it allows the front end to compile successfully.

Just a heads up: For this to work up at this stage the shape of the LAUNCH_TILE_DATA should be:

 mission {
            missionPatch
          }
without the name field.

Otherwise you get an error in the console in developer console: Uncaught (in promise) Error: Network error: Response not successful: Received status code 400. but the front end actually compiles and doesn't show any errors.

Also the Network tab shows an error with the response: message: "Cannot query field "name" on type "Mission"

@CluEleSsUK Thanks and no worries. Have a go trying out the solution posted above and seeing how it works out for you. If not, have you checked out if your types are named? I see someone had an issue with a similar error here. https://github.com/apollographql/apollo-tooling/issues/184

**Comment by mokyox** [comment]
@damirJa Thanks, that seems to have solved it. :) I added that code to `start/client/src/pages/launches.tsx` and it allows the front end to compile successfully.

Just a heads up: For this to work up at this stage the shape of the `LAUNCH_TILE_DATA` should be:

```
mission {
missionPatch
}
```
without the name field.

Otherwise you get an error in the console in developer console: `Uncaught (in promise) Error: Network error: Response not successful: Received status code 400.` but the front end actually compiles and doesn't show any errors.

Also the Network tab shows an error with the response: `message: "Cannot query field "name" on type "Mission"`

@CluEleSsUK Thanks and no worries. Have a go trying out the solution posted above and seeing how it works out for you. If not, have you checked out if your types are named? I see someone had an issue with a similar error here. apollographql/apollo-tooling#184

**Comment by mokyox** [comment]
@damirJa Thanks, that seems to have solved it. :) I added that code to `start/client/src/pages/launches.tsx` and it allows the front end to compile successfully.

Just a heads up: For this to work up at this stage the shape of the `LAUNCH_TILE_DATA` should be:

```
 mission {
            missionPatch
          }
```

without the `name` field. 

Otherwise you get an error in the console in developer console: `Uncaught (in promise) Error: Network error: Response not successful: Received status code 400`. but the front end actually compiles and doesn't show any errors. 

Also the Network tab shows an error with the response: `message: "Cannot query field "name" on type "Mission"`

@CluEleSsUK Thanks and no worries. Have a go trying out the solution posted above and seeing how it works out for you. If not, have you checked out if your types are named? I see someone had an issue with a similar error here. apollographql/apollo-tooling#184
