### ISSUE TITLE
provide path to files in docs in sections 6, 7 and 8 for Tutorial

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo#875]
### ISSUE

Hello Apollo Team! I was really learning a lot in your Tutorial in the 1st half of the setup step. Then at step 6, the file paths where no longer in the code snippet sections. It became harder and harder to follow along with where the code changes needed to be made that were shown in the code snippets. It be cool if you could add the file paths so a newbie can easily follow along. I eventually was able to figure out where my changes needed to go, but it took a lot of extra effort than the 1st half of the tutorial to get to completion of each section. 

### REFERENCES 
View a code snippet on these docs pages and you will so path is provided. 
step 6: https://www.apollographql.com/docs/tutorial/queries/
step 7: https://www.apollographql.com/docs/tutorial/mutations/
step 8: https://www.apollographql.com/docs/tutorial/local-state/

### EXPECTED BEHAVIOR

1. File Paths in code snippets are visible to aid a user in finishing the tutorial setup work.

**Comment by StephenBarlow** [comment]
Thanks for reporting! All applicable code snippets in the tutorial now have file paths in their header.
