### ISSUE TITLE
Tutorial 9 mess

### ISSUE THREAD

**Issue by TomasMoskala** [apollographql/apollo#896]
The Query local data paragraph contains quite messy code snippet. The highlight does not correspond. E.g.  function IsLoggedIn() is not in the start folder yet or  <IsLoggedIn /> tag is not highlighted, Imports section is nor complete neither exclusive, you cannot just replace all or add all, it must be pasted and corrected one by one.

In Direct cache writes paragraph the logout-button.tsx file reference is missing for the code snippet.

In general the file name should be every where a the line numbers should match or not be there at all, It's confusing.

One snippet uses 
export const resolvers: AppResolvers = {
another 
export const resolvers = {
which is an error

**Comment by StephenBarlow** [comment]
Thanks for reporting! This chapter has since been fully updated to use Apollo Client 3 local state APIs.
