### ISSUE TITLE
Get a Graph Manager API key instructions need updating

### ISSUE THREAD

**Issue by dfrho** [apollographql/apollo#909]
If you follow instructions you get blocked in this section because the provided API key and instructions from Graph Manager don't match the tutorial, resulting in "API KEY NOT FOUND" error in CLI. What's needed is to uninstall v2.14 and reinstall version 2.15 of Apollo Engine and Testing libraries, then use the __Graph Manager modal instructions__ to set up your .env file, server constructor, and CLI command. Ignore the tutorial at this point because it's dated.

**Comment by bdunks** [comment]
Thanks for the hint! The "Register Your Schema" modal in Apollo Studio indicated that it requires v2.15, but I overlooked it at first.

I might recommend that the tutorial maintainers (or whoever has the time to create a PR):

1. Update `package.json` in `server/start` to use `apollo-server` and `apollo-server-testing`  of `^2.15.0`
2. Update `package.json` to `server/start` to include `dotenv`, as it's specifically cited in the tutorial that _"Conveniently, our app already uses the `dotenv` package[...]"_
3. Add instructions to add `require('dotenv').config();` at the top of `index.js` during this step

**Comment by StephenBarlow** [comment]
Thanks for reporting! I failed to see this particular report at the time, but all three recommendations by @bdunks were implemented.
