### ISSUE TITLE
Tutorial still uses client.writeData which has been removed in Apollo 3.0

### ISSUE THREAD

**Issue by basdnguyen** [apollographql/apollo#970]
Will get an error with TypeScript `Property 'writeData' does not exist on type 'ApolloClient<any>'`

**Comment by woss** [comment]
it also uses deprecated local resolvers

**Comment by StephenBarlow** [comment]
The local state chapter of the tutorial has now been updated to reflect Apollo Client 3 APIs. Thanks for reporting!
